name: test nodes

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: demisto/opencv
    steps:
    - uses: actions/checkout@v4

    - name: Verify OpenCV installation
      run: |
        echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
        pkg-config --cflags --libs opencv4
        pkg-config --modversion opencv4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Setup Go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.6'
        check-latest: true

    - name: Install Python dependencies
      run: make install-python-deps

    - name: Lint with flake8
      run: make lint

    - name: Install ComfyUI node
      run: make install_comfyui_node

    - name: Run tests
      run: make test