name: test nodes

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: opencv-cache
      uses: UrielCh/opencv-cache-action@V1
      with:
        branch: '4.11.0'

    - name: Add OpenCV to system paths
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/build/lib" >> $GITHUB_PATH
        echo "$GITHUB_WORKSPACE/build/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/build/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$GITHUB_WORKSPACE/build/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Setup Go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.6'
        check-latest: true

    - name: Install Python dependencies
      run: make install-python-deps

    - name: Lint with flake8
      run: make lint

    - name: Install ComfyUI node
      run: make install_comfyui_node

    - name: Run tests
      run: make test