name: test nodes

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          libopencv-dev \
          build-essential

    - name: Setup Go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.6'
        check-latest: true

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements-test.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Install ComfyUI node
      run: |
        python install.py

    - name: Test with pytest
      run: |
        pytest tests