name: test nodes

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: Dovyski/setup-opencv-action@v1.1
      with:
        opencv-version: '4.11.0'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Setup Go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.6'
        check-latest: true

    - name: Install system dependencies
      run: make install-system-deps

    - name: Install Python dependencies
      run: make install-python-deps

    - name: Lint with flake8
      run: make lint

    - name: Install ComfyUI node
      run: make install_comfyui_node

    - name: Run tests
      run: make test
