name: test nodes

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: opencv-cache
      uses: UrielCh/opencv-cache-action@V1
      with:
        branch: '4.11.0'

    - name: Find OpenCV installation
      id: find_opencv
      shell: bash
      run: |
        # Ищем путь к opencv4.pc
        OPENCV_PC_PATH=$(find / -name "opencv4.pc" 2>/dev/null | head -n 1)
        if [ -z "$OPENCV_PC_PATH" ]; then
          echo "::error::opencv4.pc not found!"
          exit 1
        fi
        OPENCV_LIB_PATH=$(dirname $(dirname "$OPENCV_PC_PATH"))/lib
        echo "OPENCV_PC_PATH=$OPENCV_PC_PATH" >> $GITHUB_OUTPUT
        echo "OPENCV_LIB_PATH=$OPENCV_LIB_PATH" >> $GITHUB_OUTPUT
        echo "Found OpenCV at: $OPENCV_PC_PATH"

    - name: Add OpenCV to system paths
      shell: bash
      run: |
        echo "${{ steps.find_opencv.outputs.OPENCV_LIB_PATH }}" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${{ steps.find_opencv.outputs.OPENCV_LIB_PATH }}:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$(dirname "${{ steps.find_opencv.outputs.OPENCV_PC_PATH }}"):$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Verify OpenCV installation
      run: |
        echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
        pkg-config --cflags --libs opencv4
        pkg-config --modversion opencv4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Setup Go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.6'
        check-latest: true

    - name: Install Python dependencies
      run: make install-python-deps

    - name: Lint with flake8
      run: make lint

    - name: Install ComfyUI node
      run: make install_comfyui_node

    - name: Run tests
      run: make test